### ISSUE TITLE
Issue updating existing install after v2.6.0

### ISSUE THREAD

**Issue by TotallyAvailable** [uintdev/qrserv#27]
(leaving out the journey to actually figure out what the issue is and hoping that I'm not missing a "please do a clean install of v2.6.1" notice)

2.4->2.5->2.6 worked fine (confirmed during testing with all files freshly downloaded from the releases.), 2.6.1 and anything after fails with a generic "can't be installed on this device".

Turns out to be
INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 47 is older than current 2046

While a quick re-install is/would be no big deal, the version mismatch might still leave others stranded on 2.6.0.
(Izzy Repo appears to be stuck on 2.6 as well, with the updater likely reporting the same thing)

- The change might've also not been intentional (caused by the recent migration) ?
- I also would've assumed that the play store should warn about this during processing ? (just a guess, only played around with the GitHub versions. Giving releases outside the Play store higher version numbers appears to be the way to avoid future issues following the "small oopsie" Google decided to push through...In short, the Store version might've always used a two number version code, no idea. Also kinda irrelevant, given that you explicitly point it out in v2.6 that the signature mismatch blocks cross installs, making this a rather unexpected issue for updating through 1 source only)

**Comment by uintdev** [comment]
Looking into it, when initially building the app under Linux with v2.7.1, it reintroduced the prefix. Then when it comes to v2.7.6, the issue was resolved again (but not directly by me & with no awareness). I'm not sure what happened between v2.7.5 and v2.7.6 that fixed the issue under Flutter. If it was a regression or an issue that was still present with the tooling under Linux.

I had added the notes onto the affected releases on GitHub. Something tells me that I'm going to have to specifically check for the resulting version codes in the future, and/or hope there is a method that reliably avoids the issue entirely.

When it comes to future releases at least, it's going to be on a new stable Flutter version of which involves a different APK build system (one of the defaults being uncompressed `.so` files and them being page-aligned). Also, I'm considering to only supply the full APK rather than splitting it by ABI so that it's more convenient & that the version available on IzzyOnDroid would at least make use of 64-bit on supported devices. So, I'm not sure if that would reintroduce the issue.

We'll see what happens when the next release happens. Hopefully it'll be smoother sailing in the future.

**Comment by IzzySoft** [comment]
Btw, the issue with updating and `versionCode` still exists: 2.7.6 dropped the Flutter per-ABI prefix, so armeabi dropped from 1055 to just 56, and arm64 from 2055 to 56. Which is why IzzyOnDroid still has 2.7.5, and nobody with that (or a prior release) installed is able to update.

Is a fixed release planned – and if so, is there an ETA for that? Until then, we'll just demote the app from daily to monthly update checks, to avoid the daily cycle of download=>delete here, @uintdev (hope that's OK for you, but it's half a year now and still open).

**Comment by IzzySoft** [comment]
> The next release is planned for late February.

OK, thanks! Then we leave it at monthly checks for now (so the unneeded cycle would hopefully only appear once). Please give us a ping when the new release is ready, so we can set it to daily again.

> I can make it 2057 instead if absolutely necessary.

We carried the armeabi, so for us 1057 would suffice. But then, some folks might have used arm64, so better safe than sorry!

> I'm also considering to release it as full APK rather than split by ABI. That way, the 3 ABIs would be offered via IzzyOnDroid.

Consider APK size there as well. We have a per-app size limit of 30 MB here; so currently, we can keep 3 releases. Should the APK exceed 10 MB, we'd need to reduce that to 2 releases – and if it goes beyond 16 MB, that would mean only a single one. We could however switch to arm64 then if you wish.

> I'll be sure to ping you (likely on https://github.com/uintdev/qrserv/issues/28) when the release is ready.

Wherever, important is we receive the ping (and the note about moving the app back to daily if successful) 😉

**Comment by uintdev** [comment]
>We carried the armeabi, so for us 1057 would suffice. But then, some folks might have used arm64, so better safe than sorry!

Alright. 2057+ for next release it is.

>Consider APK size there as well. We have a per-app size limit of 30 MB here; so currently, we can keep 3 releases. Should the APK exceed 10 MB, we'd need to reduce that to 2 releases – and if it goes beyond 16 MB, that would mean only a single one. We could however switch to arm64 then if you wish.

Ah, okay. In that case, I can instead make it ARM64 only. Highly common these days and all.

>Wherever, important is we receive the ping (and the note about moving the app back to daily if successful) 😉

Sounds good. Thinking of making it a pre-release at first, just to make sure all is good. Especially when it comes to checking if it is still a reproducible build (in particular, the change made with commit 2cc63ad) -- I do still have the tooling to verify with, but just in case.

**Comment by IzzySoft** [comment]
Sounds good! We'll check the pre-release then first, before you switch the toggle. Just let us know when the day has come 😉
